name: Build Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - name: Prepare built branch content
        run: |
          # Create a temporary directory for the built content
          mkdir built-tmp
          # Copy the dist directory
          cp -r dist built-tmp/
          # Copy package.json
          cp package.json built-tmp/
          # Move into the temporary directory
          cd built-tmp
          # Initialize git and create a commit
          git init
          git add .
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -m "Build for commit $GITHUB_SHA"
      - name: Push to built branch
        run: |
          cd built-tmp
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:built
